### PR TITLE
Disable GC to prevent memory leaks.

### PR DESCRIPTION
**Pull request by SilverCory**

### CODE REVIEW

**Comment by Stylite** [comment]
Looks good to me 👍

**Comment by fofofofofofofofo** [comment]
lgtm, seems to resolve the 600MB/shard memory leaks.

**Review by fofofofofofofofo — APPROVED** [review]

**Review by Stylite — APPROVED** [review]

**Comment by SilverCory** [comment]
All checks passed, good to go @rxdn.

**Review by ducc — APPROVED** [review]
lgtm riir

**Comment by RhvsW** [comment]
lgtm !!!!!!!

**Pull request closed without merging**
